Adds user update
Emcove/emcove-front-end pull request #10
Opened 2021-06-14 23:23 UTC by julyy123

2021-06-16 23:39 UTC, micaelaRamos requested changes

2021-06-16 23:39 UTC, micaelaRamos commented on src/pages/UserProfile/UserProfile.js
> +  const loggedUser = JSON.parse(localStorage.getItem("user"));
Qué devuelve acá si el usuario no está logueado?

2021-06-16 23:39 UTC, micaelaRamos commented on src/pages/UserProfile/UserProfile.js
> +        if (resp.status === 200) {
Esto en lugar de ifs, hagamos try catch, si la respuesta no es 200 va a entrar al catch

2021-06-16 23:39 UTC, micaelaRamos commented on src/pages/UserProfile/UserProfile.js
> +      <Snackbar type="success" message="Datos guardados con éxito" show={snackbarSuccess}/>
Esto, me gustaría que nos juntemos para verlo, porque podemos hacer un objeto en el state que tenga type, y message, y lo seteas cuando terminas de hacer el apicall, quedaría algo así:

`const [snackbarData, setSnackbarData] = useState({});`

Y el componente snackbar se vería así:
`<Snackbar type={snackbarData.type} message={snackbarData.message} show={snackbarData.show} />`

Te queda un solo componente dinámico

y cuando terminas el apicall, dentro del try harías algo así:
`setSnackbarData({type: "success", message:"Datos guardados con éxito", show: true})`
y lo mismo en el catch con sus mensajes

2021-06-16 23:39 UTC, micaelaRamos commented on src/services/UserService.js
> +        if(loggedUser.avatar !== avatar){
Por qué hacemos todos estos ifs, si mandamos todos los datos rompemos algo ?

2021-06-16 23:39 UTC, micaelaRamos commented on src/pages/Login/Login.js
> +import AuthenticationService from "../../services/AuthenticationService";
Buen cambio de nombre, me gusta

2021-06-17 00:04 UTC, julyy123 commented on src/services/UserService.js
> +        if(loggedUser.avatar !== avatar){
Lo puse mas que nada para que si manda los mismos datos no lo mande en el patch así no persiste al pedo. La verdad no se cual es la forma correcta de hacerlo, si mandar todos los atributos sean o no iguales o mandar solo los distintos. En el backend anda igual si le mandas todos.

2021-06-17 00:06 UTC, julyy123 commented on src/pages/UserProfile/UserProfile.js
> +      <Snackbar type="success" message="Datos guardados con éxito" show={snackbarSuccess}/>
Dalee me parece correcto! Pensé lo mismo pero termine haciendolo así ajaj

2021-06-17 00:07 UTC, micaelaRamos commented on src/services/UserService.js
> +        if(loggedUser.avatar !== avatar){
Yo mandaría todos, solo para que el código no quede así medio desprolijo, total para el back es lo mismo, pero como te parezca mejor

2021-06-17 00:07 UTC, julyy123 commented on src/pages/UserProfile/UserProfile.js
> +  const loggedUser = JSON.parse(localStorage.getItem("user"));
Te devuelve los datos del usuario logeado que guardo cuando inicio sesión, tal vez deba usar un fetch por si los datos del usuario cambian en el medio de la sesion?

2021-06-17 02:02 UTC, micaelaRamos commented on src/pages/UserProfile/UserProfile.js
> +  const loggedUser = JSON.parse(localStorage.getItem("user"));
No, si cambian significa que fue al perfil a cambiar sus datos, cambiemos los datos ahi. En donde haces el patch para actualizar, pisa el objeto del localstorage, nos ahorramos un apicall y tenemos los datos actualizados 😄

2021-06-17 02:41 UTC, julyy123 commented on src/pages/UserProfile/UserProfile.js
> +  const loggedUser = JSON.parse(localStorage.getItem("user"));
SIii, eso ya lo estoy haciendo, la única forma de que pase eso es que tenga 2 sesiones abiertas y en 1 cambie los datos pero ya es pensar mucho jajajja

2021-06-17 02:47 UTC, merged